const products = [
  {
    id: 1,
    name: 'CodePilot Pro',
    category: 'Apps',
    price: 29.99,
    description: 'AI-powered code review assistant that catches bugs before they reach production.',
  },
  {
    id: 2,
    name: 'DeployBot',
    category: 'Tools',
    price: 14.99,
    description: 'One-click deployment pipeline for any cloud provider. Zero config needed.',
  },
  {
    id: 3,
    name: 'DesignSync',
    category: 'Apps',
    price: 19.99,
    description: 'Real-time design collaboration with version history and component libraries.',
  },
  {
    id: 4,
    name: 'API Guardian',
    category: 'Services',
    price: 49.99,
    description: 'Monitors your APIs 24/7, alerts on anomalies, and auto-generates documentation.',
  },
  {
    id: 5,
    name: 'GitFlow CLI',
    category: 'Tools',
    price: 0,
    description: 'Streamlined Git workflow manager with smart branching and merge conflict resolution.',
  },
  {
    id: 6,
    name: 'DataForge',
    category: 'Tools',
    price: 39.99,
    description: 'Transform, validate, and migrate databases with an intuitive visual interface.',
  },
  {
    id: 7,
    name: 'TestHarness',
    category: 'Services',
    price: 24.99,
    description: 'Automated testing service that generates and runs test suites from your codebase.',
  },
  {
    id: 8,
    name: 'CloudVault',
    category: 'Services',
    price: 9.99,
    description: 'Encrypted secrets management with team sharing and environment-based access control.',
  },
  {
    id: 9,
    name: 'PixelLab',
    category: 'Apps',
    price: 34.99,
    description: 'Browser-based image editor with AI-powered background removal and batch processing.',
  },
  {
    id: 10,
    name: 'LogStream',
    category: 'Tools',
    price: 17.99,
    description: 'Real-time log aggregation and search across all your microservices in one dashboard.',
  },
  {
    id: 11,
    name: 'FormCraft',
    category: 'Apps',
    price: 12.99,
    description: 'Drag-and-drop form builder with validation, conditional logic, and analytics.',
  },
  {
    id: 12,
    name: 'InfraMap',
    category: 'Services',
    price: 59.99,
    description: 'Visualize your entire cloud infrastructure and get cost-optimization recommendations.',
  },
  {
    id: 13,
    name: 'BundleCheck',
    category: 'Tools',
    price: 0,
    description: 'Analyze your JavaScript bundle size and find opportunities to reduce load times.',
  },
  {
    id: 14,
    name: 'NotifyHub',
    category: 'Services',
    price: 7.99,
    description: 'Unified notification service — email, SMS, push, and Slack from a single API call.',
  },
]

export default products
